#include <FLASH.h>

void FLASH_SET_LATENCY(uint32_t latency){
	FLASH->ACR &= ~FLASH_ACR_LATENCY_Msk;

	if(latency == FLASH_ACR_LATENCY_1WS)
		FLASH->ACR |= FLASH_ACR_LATENCY_1WS;
	else if(latency == FLASH_ACR_LATENCY_2WS)
		FLASH->ACR |= FLASH_ACR_LATENCY_2WS;
	else if(latency == FLASH_ACR_LATENCY_3WS)
		FLASH->ACR |= FLASH_ACR_LATENCY_3WS;
	else if(latency == FLASH_ACR_LATENCY_4WS)
		FLASH->ACR |= FLASH_ACR_LATENCY_4WS;
	else
		FLASH->ACR |= FLASH_ACR_LATENCY_0WS;
}